### ISSUE TITLE
Dependency installation

### ISSUE THREAD

**Issue by LeGonidec** [NablaT/angular2gen#2]
In a Yeoman generator, dependencies are usually installed (best practice) in the "installing" section.
Having it dealt directly with a function name, without being a reserved word of the Yeoman run loop will install it at the "default" level.

**Comment by alcfeoh** [comment]
When I follow the steps outlined in the README file, `gulp serve` fails. My guess is that dependencies are missing or not installed.

**Comment by NablaT** [comment]
@alcfeoh Do you have any stack trace for your error ? It will help us to fix the error, thanks :)

**Comment by alcfeoh** [comment]
Error message is along the lines of: Dependency required: ts-node/register

**Comment by NablaT** [comment]
Thanks alcefeoh. We found the origin of the problem, we are fixing it !

**Comment by NablaT** [comment]
Everything looks good from my point of view. Update your version of angular2gen by running the following command: npm install -g yo generator-angular2gen
Then, I think you should start a new project because the project generation changed. Then tell us if your new app has some errors.

We will also update the generated application for a nicer one in few days ;).
